### ISSUE TITLE
Flaky tests: parallel `pnpm -r build` in multiple beforeAll hooks clobber dist/ mid-run

### ISSUE THREAD

**Issue by kristoffeys** [kristoffeys/commonwealth#111]
Not from the #83 audit — noticed while working. `packages/cli/test/smoke.test.ts`, `packages/plugin/test/realdeps.test.ts`, and `packages/plugin/test/vendor-smoke.test.ts` each run `execFileSync('pnpm', ['-r', 'build'])` in their own `beforeAll`. vitest runs test files in parallel, so 2–3 concurrent `pnpm -r build` invocations wipe + rebuild `dist/` at the same time; a test spawning a built binary then intermittently hits `Cannot find module .../cli/dist/index.js` or `Cannot find package @commonwealth/seed/dist/index.js` (a partial-build window).

Each file passes in isolation; the failure only appears under parallel scheduling (hit ~1 in 3 full runs locally).

Fix options: build ONCE via a vitest `globalSetup` (or a pretest script) and drop the per-file `beforeAll` builds; or mark the build-dependent files to run in a single-threaded pool / serialized. Severity: low (CI-noise / developer friction), but it undermines trust in a red run.
